### ISSUE TITLE
Assets not showing after compile on production

### ISSUE THREAD

**Issue by cheeyeo** [dynamo/dynamo#101]
After compiling and deploying the app as per the instructions for heroku provided here, all the links to static assets are broken. An example of a test app can be found here: 

http://todolistdynamo.herokuapp.com/

The static_route is kept at '/static' inside dynamo.ex. The config i am using is out of the box and as follows:

```
defmodule Todolist.Dynamo do
  use Dynamo

  initializer :dynamo do
    # connect to database
  end


  config :dynamo,
    # The environment this Dynamo runs on
    env: Mix.env,

    # The OTP application associated to this Dynamo
    otp_app: :todolist,

    # The endpoint to dispatch requests to
    endpoint: ApplicationRouter,

    # The route from where static assets are served
    # You can turn off static assets by setting it to false
    static_route: "/static"

  # Uncomment the lines below to enable the cookie session store
  # config :dynamo,
  #   session_store: Session.CookieStore,
  #   session_options:
  #     [ key: "_todolist_session",
  #       secret: "mA/oBFzE9uMUNMEQ6gdyx0GwQuyznQofZG/Z3rbqa0XuVzTrjeBWrFhzluAGtld2"]

  # Default functionality available in templates
  templates do
    use Dynamo.Helpers
  end
end

```

**Comment by Tonkpils** [comment]
@cheeyeo If you check the Heroku logs, this might be the same issue I'm facing: https://github.com/goshakkk/heroku-buildpack-elixir/issues/3
and 
https://github.com/elixir-lang/elixir/issues/1046

**Comment by cheeyeo** [comment]
Hi Leo

yes i think you are right - the two issues seem to be related

**Comment by Tonkpils** [comment]
@cheeyeo Can you test out the new buildpack to make sure you issue is fixed?

**Comment by cheeyeo** [comment]
@Tonkpils Testing out the new buildpack now sorry for late response

**Comment by cheeyeo** [comment]
@Tonkpils Can confirm it is all working properly. Static assets are being picked up from priv/static path if set and the error logs inside heroku is clear. Great job guys! Thanks!
