### ISSUE TITLE
SSL Tests fail on OSX with Elixir master

### ISSUE THREAD

**Issue by relistan** [dynamo/dynamo#102]
Following the installation instructions in the Readme results in 4 test failures.  This is with a newly installed Elixir master. `brew install elixir --HEAD` after brew unlinking my previous install.

Tests were run with `MIX_ENV=test mix do test` and this is MacOS X 10.6.8.

```
=ERROR REPORT==== 23-Jul-2013::20:49:00 ===
      Conn: GET /other
    Reason: (Dynamo.NotFoundError) no route found
Stacktrace:
  test/dynamo/cowboy/router_test.exs:6: Dynamo.Cowboy.RouterTest.RouterApp.dispatch/3
  lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  lib/dynamo/cowboy/handler.ex:15: Dynamo.Cowboy.Handler.init/3
  src/cowboy_handler.erl:69: :cowboy_handler.handler_init/4
  src/cowboy_protocol.erl:514: :cowboy_protocol.execute/4
.............................................................................................

Failures:

  1) test_https_host (Dynamo.Cowboy.SSLTest)
     ** (ExUnit.ExpectationError)
                   expected: {:error, :econnrefused}
       to match pattern (=): {:ok, 200, _, client}
     at test/dynamo/cowboy/ssl_test.exs:76

  2) test_https_host_url (Dynamo.Cowboy.SSLTest)
     ** (ExUnit.ExpectationError)
                   expected: {:error, :econnrefused}
       to match pattern (=): {:ok, 200, _, client}
     at test/dynamo/cowboy/ssl_test.exs:71

  3) test_https_port (Dynamo.Cowboy.SSLTest)
     ** (ExUnit.ExpectationError)
                   expected: {:error, :econnrefused}
       to match pattern (=): {:ok, 200, _, client}
     at test/dynamo/cowboy/ssl_test.exs:81

  4) test_https_scheme (Dynamo.Cowboy.SSLTest)
     ** (ExUnit.ExpectationError)
                   expected: {:error, :econnrefused}
       to match pattern (=): {:ok, 200, _, client}
     at test/dynamo/cowboy/ssl_test.exs:66

Finished in 20.8 seconds (5.9s on load, 14.9s on tests)
235 tests, 4 failures
```

**Comment by josevalim** [comment]
It is probably related to your SSL setup. Although I am not sure where you could start looking at. :(

**Comment by davekapp** [comment]
I'm having the same problem. I've noticed that a "do you want to allow connections from _____" window opens during the tests but it closes so quickly I can't click yes. Not sure if that has something to do with it or not but it's a possibility?

**Comment by devinus** [comment]
I can confirm these tests fail for OS X. Testing if the firewall has anything to do with it...

**Comment by josevalim** [comment]
Hrm, oddly, it all passes here.

**Comment by catsby** [comment]
I get a test failure, but not related to ssl:

```
Failures:

  1) test_version (Dynamo.Cowboy.ConnectionTest)
     ** (ExUnit.AssertionError) Expected successful response, got status 500 with body "Expected :\"HTTP/1.1\" to be equal to (==) {1, 1}\n    /Users/clint/Projects/github/dynamo/test/dynamo/cowboy/connection_test.exs:19: Dynamo.Cowboy.ConnectionTest.service/1\n    /Users/clint/Projects/github/dynamo/lib/dynamo/cowboy/handler.ex:15: Dynamo.Cowboy.Handler.init/3\n    src/cowboy_handler.erl:69: :cowboy_handler.handler_init/4\n    src/cowboy_protocol.erl:523: :cowboy_protocol.execute/4\n"
     at test/dynamo/cowboy/connection_test.exs:30

Finished in 12.7 seconds (3.0s on load, 9.7s on tests)
235 tests, 1 failures
```

What is your OpenSSL version?

```
dynamo git:master ❯ openssl version
OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by josevalim** [comment]
OpenSSL version: OpenSSL 0.9.8x 10 May 2012

**Comment by devinus** [comment]
Same as @catsby. Maybe a correlation? @catsby what is your Erlang from?

**Comment by relistan** [comment]
The latest version available on 10.6 is:

```
0.9.8r 8 Feb 2011
```

That's what I'm running. Erlang:

```
Erlang R16B01 (erts-5.10.2)
```

**Comment by catsby** [comment]
@devinus pretty sure I downloaded a binary from http://elixir-lang.org/getting_started/1.html -> https://www.erlang-solutions.com/downloads/download-erlang-otp

```
$ which erl
/usr/local/bin/erl
$ erl
Erlang R16B (erts-5.10.1) [source-05f1189] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.1  (abort with ^G)
1>
```

Not homebrew...

**Comment by devinus** [comment]
@catsby Do you use Homebrew? Can you do a `which openssl`?

**Comment by catsby** [comment]
I do, and it's the homebrew openssl 

```
$  which openssl
/Users/clint/Developer/bin/openssl
```

I'm not getting SSL errors though.

**Comment by relistan** [comment]
Since it sounds like @catsby has a different failure, it's probably best if that were raised as a separate issue to keep the information here from being confused.  This issue was about failures of the SSL tests, which other people are also having (including @davekapp).

**Comment by gbmoretti** [comment]
Same problem here... on Ubuntu 12.04

`OpenSSL 1.0.1c 10 May 2012`

EDIT: Same failling tests with `OpenSSL 1.0.1e 11 Feb 2013` vesion

**Comment by devinus** [comment]
Who DOES this work for? @josevalim ? If we can get an `openssl version` and Erlang version from users who these tests pass for and those who they fail for we can begin to track this down.

**Comment by davekapp** [comment]
Here's my info (I'm one of the people the tests fail for):

OSX 10.8.4

openssl version
OpenSSL 0.9.8x 10 May 2012

elixir --version
Elixir 0.10.0

erl --version
Erlang R16B01 (erts-5.10.2) [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

mix deps
- ranch (0.8.2) [git: "git://github.com/extend/ranch.git"]
  locked at "935c7c94673027c3940a771c6e8b32f77152f1c9"
  ok
- mimetypes (e9dfab5) [git: "git://github.com/spawngrid/mimetypes.git"]
  locked at "e9dfab5aec98963589ecf13bdfcf0490667a730d"
  ok
- hackney (0.4.0) [git: "git://github.com/benoitc/hackney.git"]
  locked at "6f9b403602371bc3d4aa0b67b1e253b105075bcf"
  ok
- cowboy (0.8.4) [git: "git://github.com/extend/cowboy.git"]
  locked at "6e33274c852f60eccbdc610b0525c3541d36aa89"
  ok

**Comment by yeehaa123** [comment]
I have the same problem! Elixir 0.10, Erlang R16B01, openssl-1.0.1e

**Comment by parroty** [comment]
I was having the same issue on the following environment.
- OpenSSL 0.9.8x 10 May 2012
- Erlang R16B01 (erts-5.10.2)

However, after switching to Erlang R16B, tests started passing. 
In this issue thread, it seems like @catsby uses R16B (and also Travis CI) and he's not facing the error, though I don't have further insights...

---

/usr/local[master_]% sudo brew unlink erlang-r16
Unlinking /usr/local/Cellar/erlang-r16/R16B01... 648 links removed
/usr/local[master_]% brew versions erlang
R15B03-1 git checkout 7fc8cc0 Library/Formula/erlang.rb
R16B     git checkout 7ab778a Library/Formula/erlang.rb
R15B03   git checkout 311472d Library/Formula/erlang.rb
R15B02   git checkout 44e09dd Library/Formula/erlang.rb
R15B01   git checkout 6b8d25f Library/Formula/erlang.rb
R14B04   git checkout 0fe383a Library/Formula/erlang.rb
R14B03   git checkout 9332ca9 Library/Formula/erlang.rb
R14B02   git checkout b782d9d Library/Formula/erlang.rb
R14B01   git checkout 0476235 Library/Formula/erlang.rb
R14B     git checkout 7871a99 Library/Formula/erlang.rb
R13B04   git checkout 31f1fab Library/Formula/erlang.rb
R13B03   git checkout 729f3fa Library/Formula/erlang.rb
R13B02-1 git checkout 0d673c6 Library/Formula/erlang.rb
/usr/local[master*]% git checkout 7ab778a Library/Formula/erlang.rb

/usr/local[master*]% sudo brew install erlang
==> Downloading https://github.com/erlang/otp/archive/OTP_R16B.tar.gz

usr/local[master*]% erl
Erlang R16B (erts-5.10.1) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

**Comment by pius** [comment]
@parroty Thanks for the detailed instructions, this solved my issue.

**Comment by foxnewsnetwork** [comment]
I'm getting this exact issue. Here are my system specs:

OS: Linux Mint 13
erl: Erlang R16B
openssl version: OpenSSL 1.0.1c 10 May 2012
elixir: 0.10.2-dev
dynamo: 0.1.0-dev

**Comment by devinus** [comment]
@foxnewsnetwork Oh dear, can you copy me what your `erl` spits out. E.g. mine is:

```
Erlang R16B01 (erts-5.10.2) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
```

**Comment by hisea** [comment]
I had the same error with Erlang R16B01, Elixir master.

Downgrading to R16B with @parroty's instruction fixed my issues.

Thanks

**Comment by devinus** [comment]
Fixed by https://github.com/elixir-lang/dynamo/pull/124
