### ISSUE TITLE
Cannot relocate project files due to folder name dependency

### ISSUE THREAD

**Issue by rawtaz** [dynamo/dynamo#127]
Hi,

If you create a new Dynamo project as described in "Installation" of https://github.com/elixir-lang/dynamo, with the target folder being blog/, e.g. `mix dynamo ../blog` from within the dynamo folder, and you then do this:

```
% mkdir ../blog/source
% mv ../blog/* ../blog/.* ../blog/source
% cd ../blog/source
```

Then after a successful `mix deps.get` the `mix server` produces this:

```
% mix server
Compiled lib/blog.ex
Compiled lib/blog/dynamo.ex
Generated blog.app
** (RuntimeError) could not find endpoint ApplicationRouter, please ensure it is available
    deps/dynamo/lib/mix/tasks/server.ex:33: Mix.Tasks.Server."-run/1-fun-0-"/2
    /private/tmp/elixir-nzhO/lib/elixir/lib/enum.ex:351: Enum."-each/2-lists^foreach/1-0-"/2
    /private/tmp/elixir-nzhO/lib/elixir/lib/enum.ex:351: Enum.each/2
    deps/dynamo/lib/mix/tasks/server.ex:32: Mix.Tasks.Server.run/1
    /private/tmp/elixir-nzhO/lib/mix/lib/mix/project.ex:161: Mix.Project.recur/2
    /private/tmp/elixir-nzhO/lib/mix/lib/mix/task.ex:167: Mix.Task.run/2
    /private/tmp/elixir-nzhO/lib/mix/lib/mix/cli.ex:38: Mix.CLI.run_task/2
```

After moving the files back out of source/ into the original and now parent folder blog/ it runs fine:

```
% mv * .* ../
% cd ..
% mix server
Running Foo.Dynamo at http://localhost:4000 with Cowboy on dev
```

So, it seems that for some reason the dynamo project or something in it depends on the folder name it was created in, or I guess more specifically some component name in its source files.

I have tried `mix clean` and `mix compile` after moving it around, but it doesn't change the outcome/result.

Can we get rid of this dependency/requirement? I'd like to be able to move my projects around and be independent of which folder they reside in.

And if the matter is that somewhere in the source code there's "Blog" hardcoded, e.g. some module name, and this module name has to be the same as the folder the project resides in, then that's very unpractical. Personally I keep all my projects' source code in e.g. <domain.com or projectName>/source/, in the parent folder of source/ I keep things belonging to the project that are not version controlled.

A topic on the same note is here: https://groups.google.com/forum/#!topic/elixir-lang-core/Nq2EzspS2hI - It suggests to run the project in production mode, but that's not really a solution to the issue in the context of development mode :)

Thanks!

**Comment by rawtaz** [comment]
Is this confirmed?

**Comment by josevalim** [comment]
I haven't confirmed it in practice but if there is a "dependency", it will be in your dynamo definition or in your mix.exs file. Given your error, I would say this line is a good candidate: https://github.com/elixir-lang/dynamo/blob/master/lib/mix/tasks/dynamo.ex#L142
