### ISSUE TITLE
to_string call breaks compilation, argument error importing from cowboy in elixir

### ISSUE THREAD

**Issue by nicholasf** [dynamo/dynamo#129]
Hi,

There are a load of compilation breaks everywhere in the codebase using to_string. I've replaced the to_string calls with to_binary, instead, and that let's compilation occur. A later error, when running mix tests, appears:

```
 mix test  
** (ArgumentError) argument error
    :erlang.--(:functions, [delete_cookie: 2, delete_cookie: 3, get_cookie: 2, get_cookies: 1, put_cookie: 3, put_cookie: 4])
    src/elixir_import.erl:60: :elixir_import.calculate/7
    src/elixir_import.erl:20: :elixir_import.import/5
    src/elixir_translator.erl:146: :elixir_translator.translate_each/2
    lists.erl:1339: :lists.mapfoldl/3
    src/elixir_translator.erl:65: :elixir_translator.translate_each/2
    lists.erl:1339: :lists.mapfoldl/3
    src/elixir_clauses.erl:46: :elixir_clauses.assigns_block/6
```

**Comment by josevalim** [comment]
Welcome! :)

In order to use dynamo you need elixir master (which will be 0.10.2 soon).

## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by nicholasf** [comment]
Hi Jose. Thanks for the welcome.

I hit this issue on elixir 0.10.2.dev . I am using master.

Did there used to be a to_string on Kernel in Elixir? Has it been removed?

Cheers!
Nicholas

**Comment by josevalim** [comment]
@nicholasf On latest master, to_string is there: `elixir -e "IO.puts to_string 1"`

**Comment by nicholasf** [comment]
Thanks! Makes more sense now. I'll check my elixir setup.

**Comment by nicholasf** [comment]
Closing this. I was using the wrong version of elixir.

**Comment by devinus** [comment]
@nicholasf If you want to use a released version of Elixir, Dynamo is tagged with an Elixir version every time there's a new release.

**Comment by nicholasf** [comment]
Hey Devin,

It's cool. I'm happy working against master. I configured it on the weekend and must have made a mistake in my environment. It's working now. :)

Cheers,
Nicholas
