### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by mosesrenegade** [dynamo/dynamo#130]
I followed the instructions and now I'm getting the following compilation errors:

$ MIX_ENV=test mix do deps.get, test
All dependencies up to date
== Compilation error on file lib/dynamo/base.ex ==
*\* (SyntaxError) /Users/moses/projects/dynamo/lib/dynamo/base.ex:35: unsupported option bind_quoted given to quote
    /usr/local/Cellar/erlang-r16/R16B01/lib/erlang/lib/parsetools-2.0.9/include/yeccpre.hrl:128: :elixir_parser.yecctoken_end_location/1
    /usr/local/Cellar/erlang-r16/R16B01/lib/erlang/lib/parsetools-2.0.9/include/yeccpre.hrl:113: :elixir_parser.yeccpars1/7
    /usr/local/Cellar/erlang-r16/R16B01/lib/erlang/lib/parsetools-2.0.9/include/yeccpre.hrl:56: :elixir_parser.yeccpars0/5
    src/elixir_translator.erl:16: :elixir_translator.forms/4
    src/elixir_translator.erl:28: :elixir_translator.forms!/4
    src/elixir_compiler.erl:24: :elixir_compiler.string/2
    src/elixir_compiler.erl:48: :elixir_compiler.file_to_path/2
    /private/tmp/elixir-24F7/elixir-0.9.3/lib/elixir/lib/kernel/parallel_compiler.ex:68: Kernel.ParallelCompiler."-spawn_compilers/7-fun-0-"/3

Looks like all dependencies are in, but for some reason from the latest branch i'm getting this error.

**Comment by josevalim** [comment]
You need Elixir v0.10.2 to run Dynamo. :)

**Comment by mosesrenegade** [comment]
Awesome! I guess the README.md needs to be updated to not use the brew installed elixir which is dated.
