### ISSUE TITLE
Can't compile cowboy, dependency not available

### ISSUE THREAD

**Issue by rafaellima** [dynamo/dynamo#138]
I've successfully installed elixir and it's dependencies. But when I decided to play with dynamo, I stumbled across an error when trying do get/and compile it's dependencies:

when I run: `mix deps.get`

I got:

`Resolving deltas: 100% (3375/3375), done.
- Compiling cowboy
  ==> cowboy (compile)
  Dependency not available: ranch-.\* ({git,"git://github.com/extend/ranch.git", "0.8.5"}) `

[I believe I'm not the only one with this problem](https://github.com/extend/cowboy/issues/583) but even when I remove ranch dependencies from `mix.lock` I'm still getting errors.

Has anyone been in that situation?

**Comment by josevalim** [comment]
This issue may be related to your rebar version. How have you installed it?
Please try using the rebar version installed with mix, via "mix local.rebar"

## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by rafaellima** [comment]
I've build rebar as described in here: [building rebar](https://github.com/basho/rebar#building-rebar)
I'll try `mix local.rebar` and post the results here.

thanks,

**Comment by josevalim** [comment]
So there is a chance you are using an old rebar version. You can try this
one too: https://github.com/rebar/rebar#building-rebar

**Comment by rafaellima** [comment]
it worked just fine for me
