### ISSUE TITLE
Dynamo Fail to find ApplicationRouter

### ISSUE THREAD

**Issue by kluthen** [dynamo/dynamo#142]
Hi,

I was happily toying with dynamo on my Kubuntu, then moved to it to my Mac.
For some strange reason I happend to change the root folder name of the application. 

From this point on, I couldn't run mix server anymore.

`
** (RuntimeError) could not find endpoint ApplicationRouter, please ensure it is available
    deps/dynamo/lib/mix/tasks/server.ex:48: Mix.Tasks.Server.validate_dynamo/1
    deps/dynamo/lib/mix/tasks/server.ex:33: Mix.Tasks.Server."-run/1-fun-0-"/2
    /private/tmp/elixir-jo5d/elixir-0.10.3/lib/elixir/lib/enum.ex:351: Enum."-each/2-lists^foreach/1-0-"/2
    /private/tmp/elixir-jo5d/elixir-0.10.3/lib/elixir/lib/enum.ex:351: Enum.each/2
    deps/dynamo/lib/mix/tasks/server.ex:32: Mix.Tasks.Server.run/1
    /private/tmp/elixir-jo5d/elixir-0.10.3/lib/mix/lib/mix/project.ex:153: Mix.Project.recur/2
    /private/tmp/elixir-jo5d/elixir-0.10.3/lib/mix/lib/mix/task.ex:167: Mix.Task.run/2
    /private/tmp/elixir-jo5d/elixir-0.10.3/lib/mix/lib/mix/cli.ex:44: Mix.CLI.run_task/2
`

after doing some minor investigation on a similar case on google, I didn't find much relevant informations, aside someone having the same problem but for different reason.
(his project was camel cased, or something similar, wasn't the case with me). But it ticked that I had changed root dir name. I moved it back to the original name and then everything worked again.

This is pretty weird issue to me. Not that the name alteration has great importance to me, but weird none the less :)

**Comment by josevalim** [comment]
I will investigate. Are you running it on production or development?

**Comment by kluthen** [comment]
I dare say in development, since I don't know how to put it in production mode, i'm still learning both elixir and how to use dynamo.

Thanks for your great job ^^

**Comment by kamilc** [comment]
I have created a testing project just to troubleshoot this issue. I named the app: issue_142, then changed the folder's name to issue_142_moved confirming that I had the same issue.

I then started the app in production mode and after hitting the root route I got (in console):

Ranch listener 'Elixir.Issue_142.Dynamo.HTTP' had connection process <0.247.0> exit with reason: {[{reason,{'Elixir.RuntimeError','**exception**',<<"**could not find OTP app issue_142 for Issue_142.Dynamo. This may happen if the directory name is different than the application name.**">>}}

@josevalim: Isn't that somehow related to: https://github.com/elixir-lang/elixir/issues/1046 ?

Btw - thanks for creating Elixir and Dynamo! :)

**Comment by josevalim** [comment]
It may be related, yes. It is probably because we need to lookup for a new folder in the tmp directory but we haven't done it yet.
