### ISSUE TITLE
OPTIONS request

### ISSUE THREAD

**Issue by jbailey** [dynamo/dynamo#143]
I don't see a way to handle the OPTIONS request.  I'm basically creating a restful api server with dynamo.  Any idea how to solve this?

=ERROR REPORT==== 8-Oct-2013::15:27:21 ===
      Conn: OPTIONS /sessions
    Reason: (Dynamo.NotFoundError) no route found

EDIT: I should probably mention this is to handle CORS.

**Comment by devinus** [comment]
@jbailey Dynamo doesn't provide a helper for every HTTP verb, just the most common. `OPTIONS` could be argued to be one of those, but today you would do:

``` elixir
match "/sessions" do
  unless conn.method == "OPTIONS" do
    halt! 404, conn
  end

  # Now go crazy.
end
```

**Comment by jbailey** [comment]
Hmm, seems like I'm getting closer.  Here's my code:

``` elixir
  prepare do
    # Pick which parts of the request you want to fetch
    # You can comment the line below if you don't need
    # any of them or move them to a forwarded router
    conn = conn.put_resp_header("Access-Control-Allow-Origin", "*")
    conn = conn.put_resp_header("Access-Control-Allow-Methods", "HEAD, GET, POST, PUT, DELETE")
    conn = conn.put_resp_header("Access-Control-Allow-Credentials", true)
    conn = conn.put_resp_header("Content-Type", "text/html; charset=utf-8")
    conn.fetch([:cookies, :params])
  end

  match "/sessions" do
    if conn.method == "OPTIONS" do
      conn = conn.
      conn.resp 200, ""
    else
      user = AuthenticationQueries.authenticate(conn.params[:email], conn.params[:password])
      conn.resp 200, "ok"
    end
  end
```

I still see an error in my client that the request failed though, as opposed to the 200 I think I'm sending.

**Comment by Tonkpils** [comment]
I believe you have to add the OPTIONS method to the list of allowed in the header.

**Comment by meh** [comment]
Also beware of rogue headers JS frontend frameworks add, like `X-Sent-With` and whatnot, you have to add them to the `Access-Control-Allow-Headers`, and it doesn't support `*` so you have to read them and send them back.

I recently added CORS support to urna and it was hell, good luck.

**Comment by jbailey** [comment]
Here's what the response looks like in chrome dev tools:

```
Request URL:http://localhost:4000/sessions
Request Method:OPTIONS
Status Code:200 OK
----Request Headers view source----
Accept:*/*
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8,ky;q=0.6
Access-Control-Request-Headers:accept, origin, content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:localhost:4000
Origin:http://localhost:9000
Pragma:no-cache
Referer:http://localhost:9000/register
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.76 Safari/537.36
----Response Headersview source----
Access-Control-Allow-Credentials:true
Access-Control-Allow-Methods:OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Origin:*
cache-control:max-age=0, private, must-revalidate
connection:keep-alive
content-length:0
Content-Type:text/html; charsiet=utf-8
date:Wed, 09 Oct 2013 16:58:37 GMT
server:Cowboy
```

**Comment by meh** [comment]
You're not confirming the allowed headers it asked you about.

**Comment by jbailey** [comment]
Got it, thanks!  Now I understand CORS and headers a whole lot better.
