### ISSUE TITLE
can't fetch req_body

### ISSUE THREAD

**Issue by jbailey** [dynamo/dynamo#146]
I'm posting JSON and can't seem to get to it.  Right now I'm just trying to respond with the requested body, but later I'll decode the JSON.  I'm getting the error:

Reason: (Dynamo.Connection.UnknownFetchError) cannot fetch unknown :req_body

Here's the code:

``` elixir
prepare do
    conn.fetch([:cookies, :params, :req_body])
end

post "/" do
    conn.resp 200, conn.req_body
end
```

**Comment by devinus** [comment]
@jbailey It's `conn.fetch(:body)` not `:req_body`

**Comment by jbailey** [comment]
Sorry, was looking here:  http://elixir-lang.org/docs/dynamo/

**Comment by devinus** [comment]
An example from an app I'm writing:

``` elixir
  post "/interactions" do
    conn = conn.fetch(:body)
    interaction = JSON.decode!(conn.req_body)["interaction"]
    conn.status(201).resp_body(interaction: interaction)
  end
```

**Comment by dvv** [comment]
Staring at this, I believe `conn = conn.fetch(:body)` does automatically decode body.
What content-types are supported?
Are there plans to automate JSON body parsing (via jsx)? If not, how to augment body parser to decode based on request content-type, the right way?
TIA
