### ISSUE TITLE
Failed test on Ubuntu 12.04.3

### ISSUE THREAD

**Issue by envygeeks** [dynamo/dynamo#151]
Kernel: lts-raring 3.8.0-32-generic
Distro: Ubuntu 12.04.3

Elixir: Elixir 0.10.4-dev (head)

```
=ERROR REPORT==== 22-Oct-2013::18:33:14 ===
  Conn: GET /other
  Reason: (Dynamo.NotFoundError) no route found

  Stacktrace:
    test/dynamo/cowboy/router_test.exs:4: Dynamo.Cowboy.RouterTest.RouterApp.dispatch/3
    lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
    lib/dynamo/cowboy/handler.ex:14: Dynamo.Cowboy.Handler.init/3
    src/cowboy_handler.erl:69: :cowboy_handler.handler_init/4
    src/cowboy_protocol.erl:523: :cowboy_protocol.execute/4
```

**Comment by envygeeks** [comment]
Actually now I'm more confused because https://travis-ci.org/elixir-lang/dynamo#L381 has the same error and backtrace yet Travis claims the test passed and that nothing was wrong? I don't know if this is actually an error now or if there is something that is not covered?

**Comment by devinus** [comment]
@envygeeks It's an expected error. The exception is being tested for, in other words.

**Comment by josevalim** [comment]
Exactly. :)
