### ISSUE TITLE
Get rid of mimetypes

### ISSUE THREAD

**Issue by dvv** [dynamo/dynamo#158]
Recent cowboy depends on cowlib which has non-gen_server filename to mimetypes mapper. I've been driving the same logic in https://github.com/dvv/mimetypes.

Wonder if we could drop mimetypes dependency in favor on one of these, or similar?

I drafted patchset here: https://github.com/dvv/dynamo/tree/vd/cowboy-0.9

**Comment by devinus** [comment]
There's a pure Elixir verison of this here: https://github.com/devinus/mimetypes

I would have suggested it already, but hackney (which Dynamo uses) already depends on spawngrid/mimetypes too, so why have two libraries?

**Comment by josevalim** [comment]
hackney is used only for testing, so I don't see a problem with having both.

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by dvv** [comment]
The point is that spawngrid's version is 1) way verbose for our goals (we don't need list of mimes, etc.); 2) gen_server--call-based -- i suspect it can be a bottleneck under the load.

@devinus: nice version, btw, elixir way

**Comment by dvv** [comment]
@josevalim in my branch I managed to pass relevant tests (however, using the freshest hackney causes 34 failures of connection tests -- i don't know where to report that :) )

**Comment by josevalim** [comment]
Whatever @devinus think is best. The project is going into this hands
sooner than later. :)

**Comment by josevalim** [comment]
*his hands
- José Valimwww.plataformatec.com.br http://www.plataformatec.com.br/
  Founder and Lead Developer*

**Comment by devinus** [comment]
For sure we shouldn't just use the :mimetypes atom and override the module that hackney expects. Hackney should use spawngrid/mimetypes during testing unless hackney is developed and tested using something else upstream, or we'll be inviting all kinds of potential breakage. I have no problem with Dynamo using it's own mime types library, however. Should it be it's own library or in Dynamo itself? Dynamo.MimeTypes or something?

**Comment by dvv** [comment]
I drafted https://github.com/dvv/dynamo/blob/vd/cowboy-0.9/lib/dynamo/http/mime.ex -- Dynamo.HTTP.Mime

**Comment by dvv** [comment]
otoh, afaics new cowboy static handler serves `content-type:` using `cow_mimetypes`, and we might want to relay to it

**Comment by josevalim** [comment]
I don't think we want to depend on cowboy specific code as that would make it harder to support another web server in the future.
