### ISSUE TITLE
Override Accept:

### ISSUE THREAD

**Issue by dvv** [dynamo/dynamo#162]
Similarly to `Dynamo.Filters.MethodOverride`, it's quite useful imo to implement `accept:` header override filter, which transforms:

``` shell
GET /foo.json --> GET /foo  [{"accept", "application/json"}]
GET /foo.xml --> GET /foo  [{"accept", "text/xml"}]
GET /foo.css --> GET /foo  [{"accept", "text/css"}]
```

etc

It basically would use the same mime type analysis for path of the request and if it saw known mime type it would trim request path "extension" and set corresponding `accept:` header in `req_headers`

To illustrate, https://github.com/dvv/stable/blob/master/src/cowboy_patch.erl#L36-L50

If found irrelevant to dynamo, please, clarify how to conditionally update `req_headers` in a filter?

**Comment by josevalim** [comment]
@dvv this would be best implemented as a filter on your own application. You can store the parsed accept in `conn.assigns` or `conn.private` and use later on as you can't/shouldn't change the original req_headers.

**Comment by dvv** [comment]
Right. Thanks
