### ISSUE TITLE
Proper place to ask questions?

### ISSUE THREAD

**Issue by jbailey** [dynamo/dynamo#180]
I don't see any google group or website to ask questions.  Where is the proper place to do this?

Thanks.

**Comment by devinus** [comment]
@jbailey We could create a mailing list, but currently the best place people ask questions is `elixir-lang-talk`.

**Comment by kotedo** [comment]
Devin,

On this note; I would also like to have a dedicated dynamo discussion group.
That would make things a lot easier.

Just my $0.02
—Kai

**Comment by devinus** [comment]
I have created two new mailing lists for Dynamo:

https://groups.google.com/forum/#!forum/elixir-dynamo-talk
https://groups.google.com/forum/#!forum/elixir-dynamo-core
