### ISSUE TITLE
Cannot compile with elixir v0.12.3-dev

### ISSUE THREAD

**Issue by bobishh** [dynamo/dynamo#188]
```
$ git branch
* master
$ elixir -v
Elixir 0.12.3-dev

MIX_ENV=test mix do deps.get, test

** (CompileError) test/deps/cowboy/examples/elixir_hello_world/test/elixir_hello_world_test.exs:1: undefined function __FILE__/0
    (elixir) src/elixir_translator.erl:283: :elixir_translator.translate_arg/3
    (stdlib) lists.erl:1339: :lists.mapfoldl/3
    (stdlib) lists.erl:1340: :lists.mapfoldl/3
    (elixir) src/elixir_translator.erl:210: :elixir_translator.translate/2
    (stdlib) lists.erl:1339: :lists.mapfoldl/3
    (elixir) src/elixir_translator.erl:31: :elixir_translator.translate/2
    (elixir) src/elixir.erl:151: :elixir.quoted_to_erl/3
```

after changing to `__ENV__.file`  (since `__FILE__` is deprecated) got

```
$MIX_ENV=test mix do deps.get, test
All dependencies up to date
** (CompileError) test/deps/dynamo/test/binary/dict_test.exs:1: cannot define module Binary.DictTest because it is currently being defined
    (stdlib) erl_eval.erl:569: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:140: :elixir.eval_forms/4
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
```

**Comment by parroty** [comment]
Hi. Where (in which directory) did you execute "MIX_ENV=test mix do deps.get, test" ? 

I couldn't simulate the error, at the top directory of dynamo. Also, travis builds indicates test succeeded  2 days ago  on master (which is v0.12.3-dev).

https://travis-ci.org/dynamo/dynamo/builds

"elixir_hello_world_test.exs" seems like old example in cowboy under example/simple_ecto/deps, but I couldn't execute the test.

**Comment by bobishh** [comment]
Hmmm. I did it in dynamo directory which i cloned some time ago (don't remember actual dates), yesterday i did git pull, updated it and tryed to run 
`MIX_ENV=test mix do deps.get, test`
Now i removed this directory and cloned dynamo from the scratch, tryed to run it again and it worked, got lots of warnings, but no failures, so i guess the issue can be closed.

**Comment by nurugger07** [comment]
I pulled a fresh copy last night and was able to compile against 0.12.3-dev. I did receive the warnings and submitted a pull request. However, there is a failing router test (404 response test). I believe it's due to hackney not returning correctly. I was going to look into it but this issue probably could be closed.

**Comment by devinus** [comment]
@nurugger07 It wasnt a failing test case, but that error_logger message has been silenced. You'll see it in updates I pushed today.
