### ISSUE TITLE
Docs pages are 404

### ISSUE THREAD

**Issue by pedrosnk** [dynamo/dynamo#194]
When I try to access an doc page from the md Files. (example: @ https://github.com/dynamo/dynamo/blob/master/guides/how-to-helpers.md try to click at any helpers at the bottom of the page). It shows a 404 page form Github.

I believe that happens because before the dynamo documentation was hosted at the elixir-lang home page.

**Comment by devinus** [comment]
@pedrosnk I will redeploy docs Monday. They need to be rebuilt and rehosted.

**Comment by pedrosnk** [comment]
nice, Thanks!
