### ISSUE TITLE
Mime problems with 0.12.2

### ISSUE THREAD

**Issue by jfreeze** [dynamo/dynamo#197]
Using Elixir 0.12.2, I run the following:

git clone git@github.com:elixir-lang/dynamo.git
cd dynamo
MIX_ENV=test mix do deps.get, test
mix dynamo ~/test
cd ~/test
mix deps.get

The following error is returned...
...
Compiled src/cowboy_websocket.erl
- Compiling mime
  Compiled lib/mime.ex
  == Compilation error on file lib/mime/types.ex ==
  could not compile dependency mime, mix compile failed. You can recompile this dependency with `mix deps.compile mime` or update it with `mix deps.update mime`
  *\* (UndefinedFunctionError) undefined function: String.match?/2
  (elixir) String.match?("# This is a comment. I love comments.\t\t    -_\- indent-tabs-mode: t -_-\n", %r"^[#\n]")
  lib/mime/types.ex:10: :elixir_compiler_1."-**MODULE**/1-fun-0-"/2
  (elixir) lib/enum.ex:1139: Enum."-reduce/3-fun-0-"/3
  (elixir) lib/stream.ex:994: Stream.do_resource/5
  (elixir) lib/enum.ex:1138: Enum.reduce/3
  lib/mime/types.ex:9: (module)

**Comment by devinus** [comment]
@jfreeze Please use the elixir-0.12.2 tag of Dynamo. Dynamo master is meant to work with Elixir master.

**Comment by devinus** [comment]
@jfreeze Remember to redo `mix deps.get` and `mix compile` when you checkout the tag.

**Comment by devinus** [comment]
@jfreeze Also add tag: "elixir-0.12.2" to your mix.exs like so:

``` elixir
{ :dynamo, "~> 0.1.0-dev", github: "elixir-lang/dynamo", tag: "elixir-0.12.2" }
```

**Comment by jfreeze** [comment]
Does this line go here?

 def deps(:prod) do
    [ { :mime,   github: "dynamo/mime" },
      { :cowboy, github: "extend/cowboy", optional: true },
      { :dynamo, "~> 0.1.0-dev", github: "elixir-lang/dynamo", tag:
"elixir-0.12.2" } ]
  end

Running mix deps.get gives the error:

mix.exs:1: redefining module Dynamo.Mixfile
*\* (Mix) Trying to load Dynamo.Mixfile from
"/private/tmp/dynamo/deps/dynamo/mix.exs" but another project with the same
name was already defined at "/private/tmp/dynamo/mix.exs"

On Mon, Feb 3, 2014 at 10:50 AM, Devin Torres notifications@github.comwrote:

> @jfreeze https://github.com/jfreeze Also add tag: "elixir-0.12.2" to
> your mix.exs like so:
> 
> { :dynamo, "~> 0.1.0-dev", github: "elixir-lang/dynamo", tag: "elixir-0.12.2" }
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dynamo/dynamo/issues/197#issuecomment-33973985
> .

## 

Jim Freeze

**Comment by devinus** [comment]
@jfreeze No, sorry, it goes in the project you created when you used `mix dynamo`

**Comment by jfreeze** [comment]
Ok, I think I have this working for dev, but not production modes.

Here is what I have done:

git clone git@github.com:elixir-lang/dynamo.git
git checkout elixir-0.12.2

The mix.exs file is here: https://gist.github.com/jfreeze/8789534

I see in def project that it has

```
  elixir: "~> 0.12.0",
  version: "0.1.0-dev",
```

I don't understand why these values are what they are. Maybe they don't
matter.

I then run

  mix deps.get
  mix compile
  mix dynamo ~/testdynamo
  cd ~/testdynamo/

I now edit the mix.exs project file as in:
https://gist.github.com/jfreeze/8789534
and run

  mix deps.get
  mix compile

Running
  mix server

works. Browsing to localhost:4000, a web page says to run in production
mode, exec the command:

  MIX_ENV=prod mix do compile, server

Running that command, I get the following error:

$  MIX_ENV=prod mix do compile, server
Unchecked dependencies for environment prod:
- mimetypes (git://github.com/spawngrid/mimetypes.git)
  could not find an app file at
  _build/prod/lib/mimetypes/ebin/mimetypes.app, this may happen when you
  specified the wrong application name in your deps or if the dependency did
  not compile (which can be amended with `mix deps.compile`)
- ranch (git://github.com/extend/ranch.git)
  could not find an app file at _build/prod/lib/ranch/ebin/ranch.app, this
  may happen when you specified the wrong application name in your deps or if
  the dependency did not compile (which can be amended with `mix
  deps.compile`)
- cowlib (git://github.com/extend/cowlib.git)
  could not find an app file at _build/prod/lib/cowlib/ebin/cowlib.app,
  this may happen when you specified the wrong application name in your deps
  or if the dependency did not compile (which can be amended with `mix
  deps.compile`)
- cowboy (git://github.com/extend/cowboy.git)
  could not find an app file at _build/prod/lib/cowboy/ebin/cowboy.app,
  this may happen when you specified the wrong application name in your deps
  or if the dependency did not compile (which can be amended with `mix
  deps.compile`)
- dynamo (git://github.com/elixir-lang/dynamo.git)
  could not find an app file at _build/prod/lib/dynamo/ebin/dynamo.app,
  this may happen when you specified the wrong application name in your deps
  or if the dependency did not compile (which can be amended with `mix
  deps.compile`)
  *\* (Mix) Can't continue due to errors on dependencies

On Mon, Feb 3, 2014 at 12:28 PM, Devin Torres notifications@github.comwrote:

> @jfreeze https://github.com/jfreeze Can you Gist your entire mix.exs?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dynamo/dynamo/issues/197#issuecomment-33984078
> .

## 

Jim Freeze

**Comment by jfreeze** [comment]
Ok, I got production to run with the following commands:

 MIX_ENV=prod mix deps.get
 MIX_ENV=prod mix compile
 MIX_ENV=prod mix server

**Comment by devinus** [comment]
Correct, every MIX_ENV is entirely separate from the other, so you need to `deps.get`, `compile` and everything else in the appropriate env.

**Comment by jfreeze** [comment]
Should the boiler plate at localhost:4000 and localhost:8888 be updated?

On Mon, Feb 3, 2014 at 3:29 PM, Devin Torres notifications@github.comwrote:

> Correct, every MIX_ENV is entirely separate from the other, so you need to
> deps.get, compile and everything else in the appropriate env.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dynamo/dynamo/issues/197#issuecomment-34002266
> .

## 

Jim Freeze

**Comment by devinus** [comment]
@jfreeze Only if you want to customize the port for proxying.

**Comment by jfreeze** [comment]
No. The commands it gives do not work.

This Works:

 MIX_ENV=prod mix deps.get
 MIX_ENV=prod mix compile
 MIX_ENV=prod mix server

This does NOT work:

MIX_ENV=prod mix do compile, server

On Mon, Feb 3, 2014 at 3:33 PM, Devin Torres notifications@github.comwrote:

> @jfreeze https://github.com/jfreeze Only if you want to customize the
> port for proxying.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dynamo/dynamo/issues/197#issuecomment-34002678
> .

## 

Jim Freeze

**Comment by devinus** [comment]
@jfreeze Yes, the README needs to be updated. Since deps are compiled for **each** MIX_ENV separately we now need `MIX_ENV=prod mix do deps.get, compile, server`
