### ISSUE TITLE
Fetching in the router is the wrong place to do it

### ISSUE THREAD

**Issue by devinus** [dynamo/dynamo#20]

**Comment by josevalim** [comment]
What do you mean?

**Comment by devinus** [comment]
You want to fetch per route, not per router.

**Comment by devinus** [comment]
In Python `fetch` would be some kind of decorator function on the route itself.

**Comment by josevalim** [comment]
@devinus then you should fetch inside the route:

```
conn.fetch(:params)
```

:) This is one of the reasons I am planning to get rid of `fetch` as macro overall (you would do it inside a `prepare` or inside each route).

**Comment by devinus** [comment]
@josevalim like i said in IRC, I think being able to fetch for all routes in a router using the macro is nice. This was just a documentation issue. Maybe we can also add a conn.fetch(list) as well.
