### ISSUE TITLE
How the ^%$#$ do you run the examples?

### ISSUE THREAD

**Issue by myers** [dynamo/dynamo#201]
I think the README.md should show how to run the examples.

**Comment by mathieul** [comment]
The command line included in the comments at the beginning of each example is not enough?

``` elixir
# Run this app from Dynamo root with:
#
#     mix run -r examples/hello_world.exs --no-halt
#
```

**Comment by myers** [comment]
I did find the comments at the top of the file right after I filed this bug.  My though process went like this:
1. see websocket.exs example file from a google search of "elixir websockets".  I didn't look in the file because I'm too used to only code or useless License comments at the top of files.
2. try to remember what .exs files where
3. look at README to see if there was a mention of the examples.

What if there was a line in the README like:

There are a number of examples of dynamo features in the "examples" directory.  Look at the top of each file for directions of how to run them.

**Comment by devinus** [comment]
I would accept a PR.

**Comment by stevedomin** [comment]
Should this issue be closed now that the PR has been merged?

**Comment by myers** [comment]
:smile_cat:
