### ISSUE TITLE
Mix dynamo task not being listed/detected

### ISSUE THREAD

**Issue by HashNuke** [dynamo/dynamo#202]
I tried Dynamo master with elixir 0.12.3 and elixir master.

Couldn't find the task. (I do have mix deps compiled).

**Comment by stakoov** [comment]
this is becouse dynamo wasn't compile just run "mix compile" on only "mix"

**Comment by HashNuke** [comment]
@stakoov Sorry I did mention that I have the deps compiled already.

I cleaned it up and compiled again. Still the same.

[EDIT: Works now. I didn't realize I was compiling only the deps. Thanks for the tip]

**Comment by stakoov** [comment]
hey @HashNuke don't close issue. I think this must be bug but i'm not sure

**Comment by HashNuke** [comment]
@stakoov it worked for me after running "mix compile". I was only running "mix deps.compile" before.
