### ISSUE TITLE
Compile failing for me.

### ISSUE THREAD

**Issue by jbailey** [dynamo/dynamo#224]
Fresh erlang and elixir.

lib/dynamo/filters/exceptions/debug.ex:55: lc is deprecated, please use for comprehensions instead
lib/dynamo/filters/exceptions/debug.ex:608: lc is deprecated, please use for comprehensions instead
lib/dynamo/filters/exceptions/debug.ex:629: lc is deprecated, please use for comprehensions instead
lib/dynamo/filters/exceptions/debug.ex:639: lc is deprecated, please use for comprehensions instead

== Compilation error on file lib/dynamo/static.ex ==
*\* (ArgumentError) cannot access module File.Stat because it is not a record
    (elixir) expanding macro: Kernel.access/2
    lib/dynamo/static.ex:71: Dynamo.Static.static_path/2
    (elixir) src/elixir.erl:157: :elixir.erl_eval/2
    (elixir) src/elixir.erl:150: :elixir.eval_forms/4
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) lib/kernel/parallel_compiler.ex:91: anonymous fn/3 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by stevedomin** [comment]
What version of elixir are you using?

My guess is that you're using 0.13.2

**Comment by jbailey** [comment]
Ahh, it's broke for master?  What version should I be using?

**Comment by stevedomin** [comment]
0.13.1

Checkout to elixir stable and it will work

**Comment by jbailey** [comment]
That was it.  Thanks.

**Comment by tarantoga** [comment]
0.13.2 seems to be stable now - guess this issue should be reopened
