### ISSUE TITLE
Compilation error on file lib/dynamo/cowboy/connection.ex

### ISSUE THREAD

**Issue by Psli** [dynamo/dynamo#227]
Elixir (0.13.2)

== Compilation error on file lib/dynamo/cowboy/connection.ex ==
*\* (ArgumentError) cannot access module File.Stat because it is not a record
    (elixir) expanding macro: Kernel.access/2
    lib/dynamo/cowboy/connection.ex:155: Dynamo.Cowboy.Connection.sendfile/3

**Comment by jarednorman** [comment]
Yeah, I'm experiencing this too. Haven't made any headway on it.

**Comment by jarednorman** [comment]
I also had 0.13.0 on my system, which it compiles just fine under.

**Comment by Psli** [comment]
fixed
