### ISSUE TITLE
Serve static assets from inside a controller?

### ISSUE THREAD

**Issue by jbailey** [dynamo/dynamo#228]
I'm trying to do the front-end of my application as a SPA app.  I'm going to manage all that stuff from gulp and put the final assets into /priv/static.  So my problem is that I want to server my main index.html file out of there instead of web/templates.  How can I do that?

get "/" do
  # how do I render something from static here?
end

**Comment by alandyer** [comment]
Have you tried?

```
get "/" do
  redirect conn, to: "/static/index.html", format: :html
end
```

**Comment by jbailey** [comment]
That works. Thanks.
