### ISSUE TITLE
How do you avoid evaluation of <%= %> in embed_template

### ISSUE THREAD

**Issue by kimshrier** [dynamo/dynamo#24]
In the mix task that generates yourapp/app/templates/index.html.eex, in lib/mix/tasks/dynamo.ex on line 168 you have:

```
<title><%= @title %></title>
```

The problem is that <%= @title %> is being evaluated at the time the dynamo app is being generated so that in yourapp/app/templates/index.html.eex you have:

```
<title></title>
```

since the title variable has no value at the time the file is generated.

I have only just started looking at Elixir and dynamo and the only thing I could figure out to avoid evaluating <%= @title %> was to do the following:

```
<title><%= "<" %>%= @title %></title>
```

This feels very wrong so I am sure there is a better way.

**Comment by josevalim** [comment]
Good catch! I believe `<%%= @title %>` will work for such purposes (it was added in recent Elixir versions).

**Comment by kimshrier** [comment]
Just tried <%%= and it works as advertised.

Thank you.
Kim

**Comment by josevalim** [comment]
Awesome. If you want to send a pull request that fixes this issue in the
repository, please do so. :)
