### ISSUE TITLE
Mix do deps.get fails on elixir v1.0.2

### ISSUE THREAD

**Issue by kgish** [dynamo/dynamo#244]
I get the following error.

```
$ MIX_ENV=test mix do deps.get, test
...
** (Mix) You're trying to run :dynamo on Elixir v1.0.2 but it has declared in its mix.exs file it supports only Elixir ~> 0.13.3 or ~> 0.14.0-dev
```

**Comment by lucasmartins** [comment]
+1 here, I'm guessing Dynamo is not ready for Elixir v1 yet. 

Looks like support for 0.14/0.15 is still underway: https://github.com/dynamo/dynamo/pull/241

**Comment by Tonkpils** [comment]
From https://github.com/dynamo/dynamo/commit/3c28f27603a480d2755a89aba3a91e88df3469ce Dynamo was set on maintenance mode before Elixir v1 hit. I'm sure they would take PRs that would make it ready for v1.

**Comment by kgish** [comment]
That's too bad. In that case I guess I need to look for alternatives. The [Phoenix Framework](http://www.phoenixframework.org/) looks like a good place to start.
