### ISSUE TITLE
Test compilation fails

### ISSUE THREAD

**Issue by mikepack** [dynamo/dynamo#27]
I'm working on getting Dynamo running locally, and I'm having difficulty running the tests. I'm receiving the following error:

``` bash
$ mix test
** (MatchError) no match of right hand side value: :undefined
    /Users/Mike/Documents/Work/dynamo/lib/dynamo.ex:135: Dynamo.under_test/0
    /Users/Mike/Documents/Work/dynamo/test/dynamo/filters/head_test.exs:5: Kernel.defmodule/2
    src/elixir_compiler.erl:62: :elixir_compiler."-eval_forms/4-fun-0-"/6
    src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/4
    src/elixir_module.erl:132: :elixir_module.eval_form/5
    src/elixir_module.erl:59: :elixir_module.compile/5
    src/elixir_compiler.erl:62: :elixir_compiler."-eval_forms/4-fun-0-"/6
    src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/4
```

Some rudimentary debugging tells me the [under_test/1](https://github.com/josevalim/dynamo/blob/master/lib/dynamo.ex#L142) is not being evaluated before [under_test/0](https://github.com/josevalim/dynamo/blob/master/lib/dynamo.ex#L134) is evaluated, leaving the RHS `:undefined`. My Elixir/Erlang is weak, so I'm not able to debug much further.

I'm running Elixir HEAD on Erlang R15B03:

```
Erlang R15B03 (erts-5.9.3) [source] [64-bit] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]
```

**Comment by josevalim** [comment]
Hey @mikepack. I commented on the other thread, you need Elixir master. We will continue the discussion there. :)
