### ISSUE TITLE
mix server - The task app.start

### ISSUE THREAD

**Issue by andriytyurnikov** [dynamo/dynamo#29]
mix server
*\* (Mix) The task app.start could not be found

**Comment by josevalim** [comment]
You need Elixir master in order to run Dynamo (cloned from git and compiled with make install).

**Comment by tsloughter** [comment]
I'm seeing this using Elixir master (0.8.3.dev) when running on Heroku.

**Comment by josevalim** [comment]
@tsloughter which build pack are you using?

If you can open up the console, there are two things we could try:

1) `Mix.Task.load_all` and then `Mix.Task.all_modules` and see if `Mix.Task.App.Start` is in the list
2) `:code.get_path` and see if `lib/mix/ebin` from the elixir installation is in the path list

**Comment by tsloughter** [comment]
I'm using https://github.com/goshakkk/heroku-buildpack-elixir

1) It's Mix.Tasks.App.Start but it is there
2) So is this path

**Comment by tsloughter** [comment]
Ugh, my bad again, you can close this. I think something is wrong in the elixir buildpack that it technically fails to build something but doesn't exit properly.

So it seems the build is not working, so this is why the problem exists.
