### ISSUE TITLE
It'd be great to have `Dynamo.Cowboy.Connection.get_resp_headers/2` as a public function

### ISSUE THREAD

**Issue by Zatvobor** [dynamo/dynamo#33]
So, As a result I can remove this 
https://github.com/datahogs/couch_gears/blob/master/lib/couch_gears/mochiweb/utils.ex )

**Comment by josevalim** [comment]
What do you want to do? Get all response headers? Can't you do it as `conn.resp_headers` today?

**Comment by Zatvobor** [comment]
I just want to use `get_resp_headers/2` manually.
Take a look on, http://goo.gl/buxhI

**Comment by josevalim** [comment]
Ok, I get it. I will tackle it later!
