### ISSUE TITLE
Compilation error on trying to use Dynamo for the first time

### ISSUE THREAD

**Issue by bitemyapp** [dynamo/dynamo#34]
Elixir noob, just trying to tinker with Dynamo to see if it fits my web dev work.

After running:
`MIX_ENV=test mix do deps.get, test`

I get:

==> hackney (compile)
Compiled src/hackney_transform.erl
Compiled src/hackney_tcp_transport.erl
Compiled src/hackney_sup.erl
Compiled src/hackney_ssl_transport.erl
Compiled src/hackney_util.erl
Compiled src/hackney_url.erl
Compiled src/hackney_pool.erl
Compiled src/hackney_request.erl
Compiled src/hackney_headers.erl
Compiled src/hackney_multipart.erl
Compiled src/hackney_response.erl
Compiled src/hackney_form.erl
Compiled src/hackney_app.erl
Compiled src/hackney_deps.erl
Compiled src/hackney.erl
== Compilation error on file lib/dynamo.ex ==
*\* (SyntaxError) /Users/callen/code/dynamo/lib/dynamo.ex:179: syntax error before: '>'
    /usr/local/Cellar/erlang/R15B03-1/lib/erlang/lib/parsetools-2.0.7/include/yeccpre.hrl:128: :elixir_parser.yecctoken_end_location/1
    /usr/local/Cellar/erlang/R15B03-1/lib/erlang/lib/parsetools-2.0.7/include/yeccpre.hrl:113: :elixir_parser.yeccpars1/7
    /usr/local/Cellar/erlang/R15B03-1/lib/erlang/lib/parsetools-2.0.7/include/yeccpre.hrl:56: :elixir_parser.yeccpars0/5
    src/elixir_translator.erl:17: :elixir_translator.forms/4
    src/elixir_interpolation.erl:171: :elixir_interpolation.forms/3
    src/elixir_interpolation.erl:162: :elixir_interpolation.build_interpol/5
    src/elixir_interpolation.erl:39: :elixir_interpolation.extract/8
    src/elixir_tokenizer.erl:410: :elixir_tokenizer.handle_strings/5

**Comment by josevalim** [comment]
Are you using Elixir master? Which version does `elixir -v` report?

**Comment by bitemyapp** [comment]
Elixir 0.7.2

**Comment by josevalim** [comment]
You need Elixir master (installed from git) in order to use Dynamo (Elixir v0.8 will be out soon and this will no longer happen). You can find instructions for installing Elixir master here:

http://elixir-lang.org/getting_started/1.html

Thanks!

**Comment by pedrosnk** [comment]
I'd be nice to put a tag or a reference at the README.md to orient people to get the right release version.

For instance, today the last elixir released is the 0.7.2. So the work at the master can continue at 0.8 but there would be a download a code that works on 0.7.2. I guess it will be easier for newcomers to develop in dynamo and can continue to develop here in parallel. What do you think?

**Comment by josevalim** [comment]
I plan to do that after Elixir 0.8.0 is out. Then we will have our first official dynamo release too. :)

**Comment by pedrosnk** [comment]
:green_heart: :blue_heart: :heart: :yellow_heart: :purple_heart:
