### ISSUE TITLE
Got elixir in my env from the git repo, tried to get dynamo rolling again. Unit test fails

### ISSUE THREAD

**Issue by bitemyapp** [dynamo/dynamo#35]
From running:

`MIX_ENV=test mix do deps.get, test`

Generated dynamo.app
.....................................................................................................
=ERROR REPORT==== 24-Jan-2013::10:24:56 ===
      Conn: GET /error
    Reason: (RuntimeError) Oops
Stacktrace:
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:48: Dynamo.Filters.ExceptionsTest.ExceptionsApp.dispatch/3
  /Users/callen/code/dynamo/lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  /Users/callen/code/dynamo/lib/dynamo/http/case.ex:190: Dynamo.HTTP.Case.do_process/2
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:104: Dynamo.Filters.ExceptionsTest."test invokes handler on exceptions"/0
  /Users/callen/code/elixir/lib/ex_unit/lib/ex_unit/runner.ex:90: ExUnit.Runner.run_test/5
  lists.erl:1262: :lists.foreach/2
  /Users/callen/code/elixir/lib/elixir/lib/enum.ex:274: Enum.each/2
......
=ERROR REPORT==== 24-Jan-2013::10:24:56 ===
      Conn: GET /unauthorized
    Reason: (Dynamo.Filters.ExceptionsTest.UnauthorizedError) Unauthorized
Stacktrace:
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:58: Dynamo.Filters.ExceptionsTest.ExceptionsApp.dispatch/3
  /Users/callen/code/dynamo/lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  /Users/callen/code/dynamo/lib/dynamo/http/case.ex:190: Dynamo.HTTP.Case.do_process/2
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:110: Dynamo.Filters.ExceptionsTest."test requests status code on exceptions"/0
  /Users/callen/code/elixir/lib/ex_unit/lib/ex_unit/runner.ex:90: ExUnit.Runner.run_test/5
  lists.erl:1262: :lists.foreach/2
  /Users/callen/code/elixir/lib/elixir/lib/enum.ex:274: Enum.each/2
..................................
=ERROR REPORT==== 24-Jan-2013::10:24:57 ===
      Conn: GET /other
    Reason: (Dynamo.NotFoundError) no route found
Stacktrace:
  test/dynamo/cowboy/router_test.exs:178: Dynamo.Cowboy.RouterTest.RouterApp.dispatch/3
  lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  lib/dynamo/cowboy/handler.ex:15: Dynamo.Cowboy.Handler.init/3
  src/cowboy_protocol.erl:477: :cowboy_protocol.handler_init/4
..................................................................F.......................

1) test compiles an application (Mix.TasksTest)
  *\* (ExUnit.ExpectationError)
                    expected: "Compiled lib/my_app.ex\nCompiled lib/my_app/dynamo.ex\nMix.Project.sources is deprecated, please use Mix.Project.config_files instead\n    /Users/callen/code/elixir/lib/elixir/lib/exception.ex:125: Exception.print_stacktrace/1\n    /Users/callen/code/elixir/lib/mix/lib/mix/project.ex:114: Mix.Project.sources/0\n    /Users/callen/code/dynamo/lib/mix/tasks/compile.dynamo.ex:55: Mix.Tasks.Compile.Dynamo.do_compile/3\n    lists.erl:1197: :lists.foldl/3\n    /Users/callen/code/elixir/lib/mix/lib/mix/tasks/compile.ex:70: Mix.Tasks.Compile.\"-run/1-fun-2-\"/3\n    lists.erl:1197: :lists.foldl/3\n    /Users/callen/code/elixir/lib/mix/lib/mix/utils.ex:101: Mix.Utils.preserving_mtime/2\nGenerated my_compiled_app.app\n"
     to be a match (=~) with: %r"Compiled web/routers/application_router.ex"
  stacktrace:
    /Users/callen/code/dynamo/test/mix/tasks_test.exs:12: Mix.TasksTest."-test compiles an application/0-fun-0-"/0
    /Users/callen/code/elixir/lib/elixir/lib/file.ex:972: File.cd!/2
    /Users/callen/code/dynamo/test/mix/tasks_test.exs:8: Mix.TasksTest."test compiles an application"/0

**Comment by josevalim** [comment]
I have fixed it by pushing a fix to Elixir and Dynamo. You should be able to use Dynamo regardless (it is a minor issue just). Thanks!
