### ISSUE TITLE
Tests still breaking for dynamo on fresh installed, I pulled from origin.

### ISSUE THREAD

**Issue by bitemyapp** [dynamo/dynamo#36]
dynamo [master]$ MIX_ENV=test mix do deps.get, test

All dependencies up to date
........................................................................................................
=ERROR REPORT==== 24-Jan-2013::10:48:02 ===
      Conn: GET /error
    Reason: (RuntimeError) Oops
Stacktrace:
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:48: Dynamo.Filters.ExceptionsTest.ExceptionsApp.dispatch/3
  /Users/callen/code/dynamo/lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  /Users/callen/code/dynamo/lib/dynamo/http/case.ex:190: Dynamo.HTTP.Case.do_process/2
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:104: Dynamo.Filters.ExceptionsTest."test invokes handler on exceptions"/0
  /Users/callen/code/elixir/lib/ex_unit/lib/ex_unit/runner.ex:90: ExUnit.Runner.run_test/5
  lists.erl:1262: :lists.foreach/2
  /Users/callen/code/elixir/lib/elixir/lib/enum.ex:274: Enum.each/2
....
=ERROR REPORT==== 24-Jan-2013::10:48:02 ===
      Conn: GET /unauthorized
    Reason: (Dynamo.Filters.ExceptionsTest.UnauthorizedError) Unauthorized
Stacktrace:
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:58: Dynamo.Filters.ExceptionsTest.ExceptionsApp.dispatch/3
  /Users/callen/code/dynamo/lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  /Users/callen/code/dynamo/lib/dynamo/http/case.ex:190: Dynamo.HTTP.Case.do_process/2
  /Users/callen/code/dynamo/test/dynamo/filters/exceptions_test.exs:110: Dynamo.Filters.ExceptionsTest."test requests status code on exceptions"/0
  /Users/callen/code/elixir/lib/ex_unit/lib/ex_unit/runner.ex:90: ExUnit.Runner.run_test/5
  lists.erl:1262: :lists.foreach/2
  /Users/callen/code/elixir/lib/elixir/lib/enum.ex:274: Enum.each/2
.................................
=ERROR REPORT==== 24-Jan-2013::10:48:02 ===
      Conn: GET /other
    Reason: (Dynamo.NotFoundError) no route found
Stacktrace:
  test/dynamo/cowboy/router_test.exs:178: Dynamo.Cowboy.RouterTest.RouterApp.dispatch/3
  lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  lib/dynamo/cowboy/handler.ex:15: Dynamo.Cowboy.Handler.init/3
  src/cowboy_protocol.erl:477: :cowboy_protocol.handler_init/4
..................................................................F.......................

1) test compiles an application (Mix.TasksTest)
  *\* (ExUnit.ExpectationError)
                    expected: "Compiled lib/my_app.ex\nCompiled lib/my_app/dynamo.ex\nGenerated my_compiled_app.app\n"
     to be a match (=~) with: %r"Compiled web/routers/application_router.ex"
  stacktrace:
    /Users/callen/code/dynamo/test/mix/tasks_test.exs:12: Mix.TasksTest."-test compiles an application/0-fun-0-"/0
    /Users/callen/code/elixir/lib/elixir/lib/file.ex:972: File.cd!/2
    /Users/callen/code/dynamo/test/mix/tasks_test.exs:8: Mix.TasksTest."test compiles an application"/0

231 tests, 1 failures.

**Comment by josevalim** [comment]
You need to have both Dynamo and Elixir master. In your elixir git checkout, just do:

```
git pull --rebase
make
```

And you should be good.

PS: Sorry for the issues but we are in the middle of Elixir v0.8, so things are changing quickly. :)
