### ISSUE TITLE
Problem fetching latest updates

### ISSUE THREAD

**Issue by kimshrier** [dynamo/dynamo#42]
I have cloned dynamo into my github account and then cloned that onto my laptop.  I am having a problem fetching the latest updates so that I can merge them to my github clone.

On my laptop, I have:

```
$ git remote -v
origin  https://github.com/kimshrier/dynamo.git (fetch)
origin  https://github.com/kimshrier/dynamo.git (push)
upstream    https://github.com/josevalim/dynamo.git (fetch)
upstream    https://github.com/josevalim/dynamo.git (push)
```

When I try to fetch the latest updates, I get:

```
$ git fetch upstream
fatal: https://github.com/josevalim/dynamo.git/info/refs?service=git-upload-pack not found: did you run git update-server-info on the server?
```

I am not sure how to remedy this but the error message implies that something needs to be done on https://github.com/josevalim/dynamo.git.

Any help would be appreciated.

**Comment by rpmessner** [comment]
The repository was moved to https://github.com/elixir-lang/dynamo, you should reset your upstream remote.

**Comment by rafaelfranca** [comment]
Yes. You need to change your remote

**Comment by kimshrier** [comment]
thanks.

**Comment by rafaelfranca** [comment]
let us know if you still need some help

**Comment by kimshrier** [comment]
Everything is working fine now.  Really appreciate the quick response.

**Comment by rafaelfranca** [comment]
Glad to know. Enjoy!
