### ISSUE TITLE
Following getting started directions - ApplicationRouter not loaded - Dev environment.

### ISSUE THREAD

**Issue by alanpeabody** [dynamo/dynamo#43]
When following the getting started directions I am experiencing:

```
$ mix server
** (RuntimeError) could not find endpoint ApplicationRouter, please ensure it is available
    /home/alan/AgilionApps/Projects/Chatter/deps/dynamo/lib/mix/tasks/server.ex:16: Mix.Tasks.Server."-run/1-fun-0-"/1
...
```

However, running in production gets me a functional application:

```
$ MIX_ENV=prod mix do clean, compile, server
```

I can also compile the file manually and run in dev, but I get template errors:

```
$ elixirc -o tmp/dev/chatter/ebin/ -pa deps/dynamo/ebin web/routers/application_router.ex
$ mix server
```

I have been digging around in the Dynamo.Loader module with no success.

If it helps I am running Ubuntu, not OSX.

**Comment by josevalim** [comment]
Hello @alanpeabody, if you run `mix test`, do all tests pass for you?

I was able to successfully boot up an application in development, so I will need more information to reproduce the issue. If you are on #irc, please hit me up.

**Comment by alanpeabody** [comment]
@josevalim I will not be able to jump back into this until the weekend, at which point I will make sure I am on IRC, but I do know 4 tests in dynamo itself are failing, but they all seem related to cowboy.

I am running master elixir branch and master dynamo branch.

**Comment by josevalim** [comment]
Ok, pls let me know then!

**Comment by philss** [comment]
Hi @josevalim ,

I got the same number of failures(4) when running tests:

```
=ERROR REPORT==== 22-Feb-2013::03:01:37 ===
      Conn: GET /other
    Reason: (Dynamo.NotFoundError) no route found
Stacktrace:
  test/dynamo/cowboy/router_test.exs:6: Dynamo.Cowboy.RouterTest.RouterApp.dispatch/3
  lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  lib/dynamo/cowboy/handler.ex:15: Dynamo.Cowboy.Handler.init/3
  src/cowboy_protocol.erl:477: :cowboy_protocol.handler_init/4

Failures:

  1) test_https_host (Dynamo.Cowboy.SSLTest)
     ** (MatchError) no match of right hand side value: {:error,:econnrefused}
     at test/dynamo/cowboy/ssl_test.exs:76

  2) test_https_host_url (Dynamo.Cowboy.SSLTest)
     ** (MatchError) no match of right hand side value: {:error,:econnrefused}
     at test/dynamo/cowboy/ssl_test.exs:71

  3) test_https_port (Dynamo.Cowboy.SSLTest)
     ** (MatchError) no match of right hand side value: {:error,:econnrefused}
     at test/dynamo/cowboy/ssl_test.exs:81

  4) test_https_scheme (Dynamo.Cowboy.SSLTest)
     ** (MatchError) no match of right hand side value: {:error,:econnrefused}
     at test/dynamo/cowboy/ssl_test.exs:66

Finished in 12.5 seconds
234 tests, 4 failures
```

But my app runs normally(I have not tested SSL), both in development and production env. I'm running on Linux(Fedora 16) with elixir and dynamo from master branch.

**Comment by devinus** [comment]
@philss What version of Erlang?

**Comment by philss** [comment]
@devinus Erlang R15B01 (erts-5.9.1)

**Comment by alanpeabody** [comment]
I am seeing the same issues in dynamo master as @philss.

`MIX_ENV=test mix do deps.clean, deps.get, clean, test` results in the same 4 failures.

I am also running Erlang R15B01 (erts-5.9.1) (installed from Ubuntu repositories).

**Comment by alanpeabody** [comment]
@l4u, Thanks, but it looks like it is already installed -- will pursue this further.

@josevalim I tracked down my original issue. Generating a dynamo application with a camel case name results in the application router error, however I see no difference in the application generated.

`mix dynamo ~/cap_test` produces a working application (tests pass, server starts)
`mix dynamo ~/CapTest` produces a non-functional application (tests will not run, server will not start)

I can work on a test case if this is not the expected behavior.

**Comment by josevalim** [comment]
Oh, it is definitely a bug, good catch! A test case is welcome!

## 

*
José Valim
www.plataformatec.com.br
Founder and Lead Developer
*
