### ISSUE TITLE
Set Port at Runtime in Production

### ISSUE THREAD

**Issue by tsloughter** [dynamo/dynamo#49]
In order to run on services like Heroku there must be a way to set the port number when the application is started. While Heroku sets the os var PORT it would be better to be more generic and either let a port be passed somewhere as an argument in the code or to mix like: mix server --port 8000u

**Comment by skull-squadron** [comment]
:+1:

A working heroku example project would also be awesome.

**Comment by skull-squadron** [comment]
From https://github.com/goshakkk/dynamo_demo/blob/master/Procfile

But something like `mix server -p=8000` doesn't seem to work interactively (always comes up on port 4000 (dev) or 8888 (prod)).

**Comment by tsloughter** [comment]
That is an old demo, it no longer works.
