### ISSUE TITLE
Directory name different from the application name.

### ISSUE THREAD

**Issue by meh** [dynamo/dynamo#50]
Is there a way to have a different root directory name from the application name?

If the root directory name is different it doesn't work in test environment (can't find ApplicationRouter), and in production environment it throws an error after serving the request (talking about directory name being different).

Depending on the directory name to make `mix server` work seems to be kind of prone to errors.

**Comment by josevalim** [comment]
You can't really. Erlang relies on those to have the same name, otherwise
some operations in the :code module do not work as expected.

On Saturday, March 30, 2013, meh. wrote:

> Is there a way to have a different root directory name from the
> application name?
> 
> If the root directory name is different it doesn't work in test
> environment (can't find ApplicationRouter), and in production environment
> it throws an error after serving the request (talking about directory name
> being different).
> 
> Depending on the directory name to make mix server work seems to be kind
> of prone to errors.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/elixir-lang/dynamo/issues/50
> .

## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by meh** [comment]
Oh snap, thanks, didn't know.
