### ISSUE TITLE
Exception handler needs to be sent as text/html

### ISSUE THREAD

**Issue by devinus** [dynamo/dynamo#55]

**Comment by devinus** [comment]
What was the resolution?

**Comment by josevalim** [comment]
Oops, none. :) If you want to send a pull request, feel free. :)

**Comment by devinus** [comment]
@josevalim Yeah. I've been meaning to have a pow-wow with you about some Dynamo issues/ideas once I get back from vacation next week.

**Comment by devinus** [comment]
Uh, not sure what happened, but this doesn't happen during testing for me anymore. `¯\_(ツ)_/¯`
