### ISSUE TITLE
static content should be at / instead of /static

### ISSUE THREAD

**Issue by cbd** [dynamo/dynamo#56]
For example, in a default project, the favicon.ico is found at http://localhost:4000/static/favicon.ico, which is incorrect per international favicon society conventions. Seems like leaving static content in /priv/static is fine but referencing it at / is more common and allows easier porting of Sinatra and Rails apps to Dynamo.

**Comment by skull-squadron** [comment]
Yeap, I had the same issue.

At first, I hacked in a `filter Dynamo.Filters.Static.new("/", "priv/static")` in the ApplicationRouter, but then things were getting served twice (/ and /static).

This did the trick in `lib/<name>/dynamo.ex`

``` diff
-    static_route: "/static"
+    static_route: "/"
```
