### ISSUE TITLE
cannot fetch unknown :req_headers

### ISSUE THREAD

**Issue by skull-squadron** [dynamo/dynamo#58]
The goal is to get the Host header

```
prepare do
  conn.fetch([:cookies, :params, :req_headers])
end

....

conn.req_headers['Host']
```

Updated: because were not using CGI. :)

**Comment by josevalim** [comment]
I think it is just `:headers`. This is a good point though, the name of the things you are fetching should probably be the name of the function you call to retrieve them. :)

**Comment by skull-squadron** [comment]
Thanks for the quick reply.

Changing `:req_headers` -> `:headers` resulted in "did not fetch req_headers from request, call 'conn.fetch :req_headers' in order to fetch it"

Also tried `conn.req.headers` and `conn.headers`, in addition to `conn.req_headers`

**Comment by skull-squadron** [comment]
Would `:headers` refer to request or response headers?

Looking at Sinatra, it  `request['HEADER']` and `response['OTHER_HEADER'] = value` ...

Is something like `conn.req_headers['HEADER']` and `conn.resp_headers['OTHER_HEADER'] = value` supported (perhaps with aspects `:req_headers` and `:resp_headers`)?

**Comment by skull-squadron** [comment]
Looks like there's no need for `:resp_headers` since it's always there ... `conn.put_resp_header("server", "custom/1.0.0")` works without additional aspects

**Comment by josevalim** [comment]
@steakknife it is `conn.fetch(:headers)`. I just checked the source:

https://github.com/elixir-lang/dynamo/blob/master/lib/dynamo/cowboy/connection.ex#L192

The reason I originally called it `:headers` is because you can't fetch the response headers, this is something that you set yourself. You can only really fetch information from the request.

**Comment by skull-squadron** [comment]
Makes sense.  request stuff is input, response stuff is output from app code perspective.

**Comment by skull-squadron** [comment]
Found it, thanks!

`conn.fetch(:headers).req_headers['host'] # grab the Host header`

This also works, assuming all actions need request headers:

```
prepare do
  conn = conn.fetch([:cookies, :params, :headers])
end

.
.
.

host = conn.req_headers['host']

```

Also found that it's lower-casing all of the header fields.  (Thank you `IO.inspect`)

```
#Binary.Dict<[
  {"host","localhost:4000"},
  {"user-agent","Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:20.0) Gecko/20100101 Firefox/20.0"},
  {"accept","text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
  {"accept-language","en-US,en;q=0.5"},
  {"accept-encoding","gzip, deflate"},
  {"dnt","1"},
  {"connection","keep-alive"},
  {"cache-control","max-age=0"}
]>
```

PEBKAC, as usual.

Thanks for the help. :)
