### ISSUE TITLE
undefined Enum.member

### ISSUE THREAD

**Issue by tsloughter** [dynamo/dynamo#59]
I checkedout the current master and created a new dynamo project from it but it now fails on an undefined function:

```
Compiled lib/dynamo_demo.ex
== Compilation error on file lib/dynamo_demo/dynamo.ex ==
** (UndefinedFunctionError) undefined function: Enum.member?/2
    Enum.member?([], Dynamo.Base)
    /home/tristan/Devel/dynamo_demo/deps/dynamo/lib/dynamo/utils/once.ex:23: Dynamo.Utils.Once."MACRO-use_once"/2
    /home/tristan/Devel/dynamo_demo/lib/dynamo_demo/dynamo.ex:2: Dynamo.Utils.Once.use_once/1
```

**Comment by josevalim** [comment]
Sorry, You will need Elixir master to run Dynamo master. brew install
elixir --head should do it!


## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by tsloughter** [comment]
Yup, my bad. Was doing this in short spurts I had in the day and didn't think to do that first before opening a ticket :). Thanks!

And would be nice if it was as easy as 'brew install elixir --head' on Ubuntu :)
