### ISSUE TITLE
Enum.member? isn't yet available in Elixir 0.8.2

### ISSUE THREAD

**Issue by skull-squadron** [dynamo/dynamo#60]
```
** (UndefinedFunctionError) undefined function: Enum.member?/2
    Enum.member?([], Dynamo.Base)
    ..../lib/dynamo/utils/once.ex:25: Dynamo.Utils.Once."MACRO-use_once"/2
    ..../test/dynamo/cowboy/router_test.exs:7: Dynamo.Utils.Once.use_once/1
```

Solved by `brew upgrade elixir --HEAD`

**Comment by skull-squadron** [comment]
Note: most people will probably want **stable** releases of Elixir and Dynamo.  I wouldn't expect any support on unstable.

**Comment by josevalim** [comment]
@steakknife Dynamo is alpha software and it is always unstable. :) Dynamo will start to get proper and stable releases very likely just after Elixir v1.0 comes out.
