### ISSUE TITLE
{:undef,[{DynamoHerokuDemo.Dynamo.CompiledTemplates,:requires_precompilation?,[],[]}

### ISSUE THREAD

**Issue by tsloughter** [dynamo/dynamo#65]
So yesterday https://github.com/tsloughter/dynamo_heroku_demo worked fine on Heroku. Doing a fresh deploy myself, and others have experienced the same, the following crash occurs on startup:

```
** (Mix) Could not start application dynamo_heroku_demo: {:bad_return,{{DynamoHerokuDemo,:start,[:normal,[]]},{:EXIT,{:undef,[{DynamoHerokuDemo.Dynamo.CompiledTemplates,:requires_precompilation?,[],[]},{Enum,:do_all?,2,[file: '/tmp/build_2uekmxivc70z3/ex/lib/elixir/lib/enum.ex', line: 1231]},{DynamoHerokuDemo.Dynamo,:initializer_start_dynamo_renderer,0,[file: '/tmp/build_2uekmxivc70z3/deps/dynamo/lib/dynamo.ex', line: 192]},{DynamoHerokuDemo.Dynamo,:run_initializers,0,[file: '/tmp/build_2uekmxivc70z3/deps/dynamo/lib/dynamo/base.ex', line: 191]},{DynamoHerokuDemo.Dynamo,:start_link,1,[file: '/tmp/build_2uekmxivc70z3/deps/dynamo/lib/dynamo.ex', line: 152]},{:application_master,:start_it_old,4,[file: 'application_master.erl', line: 274]}]}}}}
```

It is the same mix.lock as the working deployed copy so I'm not sure where to look for what could have changed.

Does the error message make any sense to you for where I should be looking?

**Comment by josevalim** [comment]
Updating Dynamo and Elixir to master have fixed the issue. It is probably related to the latest manifest changes in Mix. I plan to release a new Elixir version this weekend, so things will get a bit more stable. :)

**Comment by tsloughter** [comment]
Thanks, that worked. 

I'll be trying to keep up with this and follow as elixir/dynamo masters change to keep it working on Heroku. I'll try not to have to open tickets when it is cases like this again :)

**Comment by josevalim** [comment]
Nah, feel free to open tickets or ping me on irc if you need too! :)
