### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by tarantoga** [dynamo/dynamo#66]
Just wanted to try dynamo, getting however compilation error when running MIX_ENV=test mix do deps.get, test

here details:
All dependencies up to date
Compiled lib/dynamo/app.ex
Compiled lib/dynamo/base.ex
Compiled lib/dynamo/connection/behaviour.ex
Compiled lib/dynamo/cowboy.ex
Compiled lib/dynamo/cowboy/handler.ex
Compiled lib/dynamo/connection/query_parser.ex
== Compilation error on file lib/dynamo/filters/exceptions.ex ==
*\* (CompileError) /Users/tarantoga/Projects/Elixir/dynamo/lib/dynamo/filters/exceptions.ex:6: cannot import Exception.format_stacktrace_entry/2 because it doesn't exist
    /opt/local/lib/erlang/lib/parsetools-2.0.9/include/yeccpre.hrl:128: :elixir_parser.yecctoken_end_location/1
    /opt/local/lib/erlang/lib/parsetools-2.0.9/include/yeccpre.hrl:113: :elixir_parser.yeccpars1/7
    /opt/local/lib/erlang/lib/parsetools-2.0.9/include/yeccpre.hrl:56: :elixir_parser.yeccpars0/5
    src/elixir_translator.erl:17: :elixir_translator.forms/4
    src/elixir_translator.erl:27: :elixir_translator.forms!/4
    src/elixir_compiler.erl:25: :elixir_compiler.string/2
    src/elixir_compiler.erl:49: :elixir_compiler.file_to_path/2
    /private/tmp/elixir-XQKM/elixir-0.8.2/lib/elixir/lib/kernel/parallel_compiler.ex:56: Kernel.ParallelCompiler."-spawn_compilers/7-fun-0-"/3

any idea what the problem is? 

cheers

**Comment by josevalim** [comment]
Dynamo master runs on latest Elixir. Maybe you have an older version? If so, please install v0.9!

**Comment by tarantoga** [comment]
yep, that was it, thanks!
