### ISSUE TITLE
When creating a new app, warn if name is dynamo

### ISSUE THREAD

**Issue by timbuchwaldt** [dynamo/dynamo#67]
If you create a new application and call it "dynamo", the mix build breaks because you can't build dynamo (as your app already defines Dynamo.Mixfile)
This should be prevented by checking the name in the task.

**Comment by josevalim** [comment]
Good catch! Could you please send a pull request?

In fact, it would be best if we checked for any defined constant... basically we need to check something like this:

```
if Code.ensure_loaded?(Module.concat([module_name])) do
  # do something, module already defined
end
```

**Comment by timbuchwaldt** [comment]
Done, i created a PR at #68
