### ISSUE TITLE
Should have a websocket demo ?

### ISSUE THREAD

**Issue by itifai** [dynamo/dynamo#7]

**Comment by josevalim** [comment]
It will. It is WIP and websockets are on the pipeline.

**Comment by itifai** [comment]
Thank you. :) Looking forward to the release.

**Comment by phuesler** [comment]
I would prefer to have a Server Sent Event demo first, because it builds on http and IMHO, server side push is one of the most common use cases.

**Comment by foobarto** [comment]
are we there yet? :)

I see that lib/dynamo/cowboy/handler.ex has websocket handler functions - anyone would mind posting here a simple code snippet on how to handle websocket requests?

**Comment by josevalim** [comment]
Nope, we are not. If there is a need to use websockets, I would use cowboy directly because their API is expected to be more stable.
