### ISSUE TITLE
SSL examples doesn't work as expected

### ISSUE THREAD

**Issue by jjh42** [dynamo/dynamo#71]
I followed the SSL example but whenever I connect to the SSL port I receive the error (in my browser) of "No data received".

Running `mix run -r examples/ssl.exs --no-halt` in the dynamo folder has the same result, HTTP works fine but HTTPS fails with "no data received" and nothing printed in the output console.

I'd be happy to try and fix this - if anyone had any pointers that'd be great. `Dynamo.Cowboy.Handler.init` and `handle` don't ever appear to be called when a HTTPS request in received.

**Comment by philss** [comment]
Hi @jjh42 ,

I'm trying to reproduce the error. But seems that everything works good.
My steps were:
1. update elixir with the lastest version from master (https://github.com/elixir-lang/elixir/commit/a42725910f4059366f8e68d8cb1a3358a27238c7)
2. update dynamo with the lastest version from master (e03ff7d50b2b220121a2a30b0bde42faeaca5e07)
3. update dynamo dependencies and run tests -> `MIX_ENV=test mix do deps.get, test`
4. create a new app 
5. test SSL based on the dynamo SSL guide -> works good
6. test your command in dynamo root path ( `mix run -r examples/ssl.exs --no-halt` )
7. make a request in the browser -> `https://localhost:3031/` -> works good
8. make a request using curl -> `curl -I https://localhost:3031/ --insecure` -> works good.

Have you checked if the problem still existing in the recent version of dynamo?

PS.: I get the error when I try to connect using the URL without `https`
