### ISSUE TITLE
How do you guys format Elixir code?

### ISSUE THREAD

**Issue by derekchiang** [dynamo/dynamo#72]
I was reading Dynamo's source code and I found the code impeccably formatted.  I was just wondering if you guys are using some special tools to do the formatting, and if so could you tell us what they are?

**Comment by rafaelfranca** [comment]
Hi.

There are a few tools for the different editors in the organization home https://github.com/elixir-lang.

We are using these tools

**Comment by acrolink** [comment]
Now 3 years on, is there any tool that can be used on Windows or any online formatting tools? Thank you.

**Comment by devinus** [comment]
@acrolink https://medium.com/@fazibear/automated-elixir-code-review-with-github-credo-and-travis-ci-986cd56b8f02#.6bru0gsbk
