### ISSUE TITLE
Failure when deploy to another machine

### ISSUE THREAD

**Issue by derekchiang** [dynamo/dynamo#74]
I've been able to run my Dynamo site pretty well locally (thank you guys so much by the way :D), but today when I tried to deploy my site to another machine, I got this error:

```
root@ubuntu-13:~/Try-Elixir# mix server
Compiled lib/try_elixir.ex
Compiled lib/try_elixir/dynamo.ex
Generated try_elixir.app
** (RuntimeError) could not find endpoint ApplicationRouter, please ensure it is available
    /root/Try-Elixir/deps/dynamo/lib/mix/tasks/server.ex:33: Mix.Tasks.Server."-run/1-fun-0-"/2
    lists.erl:1313: :lists.foreach/2
    /root/elixir/lib/elixir/lib/enum.ex:284: Enum.each/2
    /root/Try-Elixir/deps/dynamo/lib/mix/tasks/server.ex:32: Mix.Tasks.Server.run/1
    /root/elixir/lib/mix/lib/mix/project.ex:172: Mix.Project.recur/2
    /root/elixir/lib/mix/lib/mix/cli.ex:38: Mix.CLI.run_task/2
    src/elixir_compiler.erl:65: :elixir_compiler."-eval_forms/4-fun-0-"/7
```

What could be wrong?  I couldn't figure it out...  I've made sure that I run `mix deps.get` before I run `mix server`.

**Comment by derekchiang** [comment]
To clarify, I'm using Erlang R16B with the latest Elixir.

**Comment by josevalim** [comment]
For production, you need to explicitly compile your dynamo before with `mix compile`, that's what is missing. :)

Btw, let's leave this open because the error message could be better (or we could simply compile it automatically).

**Comment by derekchiang** [comment]
@josevalim Did you mean I need to run `mix compile` in my Dynamo's root directory?  I just tried and it didn't solve the problem.  `mix compile` prints no output and when I run `mix server` I still get the same error.

**Comment by derekchiang** [comment]
I tried `MIX_ENV=prod mix do compile, server` and it worked.  Still not sure why it didn't work in development mode though.

**Comment by josevalim** [comment]
In dev, we precompile on demand. For prod, you need to explicitly compile
it as you don't want to precompile on every request for performance reasons.

## 

*
José Valim
www.plataformatec.com.br
Founder and Lead Developer
*
