### ISSUE TITLE
Sendfile support?

### ISSUE THREAD

**Issue by Psli** [dynamo/dynamo#79]

**Comment by jjh42** [comment]
Could you explain a bit more what you mean. Simple Asynchronous File Transfer? How does it fit in the context of a web framework.

**Comment by josevalim** [comment]
Check out for conn.sendfile in our docs, it already works today.

## 

_José Valim_
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by Psli** [comment]
Thanks, found it.
Sorry for my carelessness.

**Comment by dvv** [comment]
Wonder whether there are plans to extend sendfile support to honor `Range: bytes=Start-End`?
