### ISSUE TITLE
Wrong layout path in guide "How to render templates with layouts"

### ISSUE THREAD

**Issue by jdrexler** [dynamo/dynamo#81]
The guide "How to render templates with layouts" says that the layout file should be placed at the file path "web/templates/main.html.eex". This is not working for me.
Instead, than placing the file at "web/templates/layouts/main.html.eex" it works as expected.

**Comment by josevalim** [comment]
Yes, this sounds correct, thank you! Can you please send a pull request fixing the guide? :D
