### ISSUE TITLE
`mix deps.get` fails (might be Windows-related)

### ISSUE THREAD

**Issue by ToJans** [dynamo/dynamo#84]
When I try to get the dependencies, I got some errors, so I tried unlocking the dependencies. This helps, but it looks like the checkout does not work with tags:
![image](https://f.cloud.github.com/assets/155977/680644/ecdc569a-d996-11e2-96fc-d95860ced5cc.png)

**Comment by josevalim** [comment]
Can you pls try a mix deps.clean to force a full refetch of dependencies?

**Comment by ToJans** [comment]
![image](https://f.cloud.github.com/assets/155977/680681/769f9350-d998-11e2-8e06-b60dedf23450.png)

**Comment by josevalim** [comment]
Yeah, bug. Probably a windows one. :)

**Comment by josevalim** [comment]
Btw, once we are past the elixir failures, the mix failures will show up.
We can get them today by running "make test_mix" in the Elixir repository.

**Comment by ToJans** [comment]
Still an issue...
![image](https://f.cloud.github.com/assets/155977/868514/658e3dbc-f7a9-11e2-8c54-acef729fdbd6.png)

**Comment by ericmj** [comment]
@ToJans This might get fixed by this PR: https://github.com/elixir-lang/elixir/pull/1510

**Comment by ToJans** [comment]
This works with the latest version from the master!!!
