### ISSUE TITLE
Localhost cookies from rails apps brake development environment

### ISSUE THREAD

**Issue by andriytyurnikov** [dynamo/dynamo#86]
Cowboy answers with HTTP 400, Bad request
Tests are fine, sure
"cowboy": {:git,"git://github.com/extend/cowboy.git","6e33274c852f60eccbdc610b0525c3541d36aa89"}

**Comment by devinus** [comment]
@andriytyurnikov Can you confirm if this is still an issue?

**Comment by andriytyurnikov** [comment]
@devinus could not reproduce nowadays - looks fine

**Comment by devinus** [comment]
Thanks for taking a look again.
