### ISSUE TITLE
Error on step 3 of installation

### ISSUE THREAD

**Issue by wchrisjohnson** [dynamo/dynamo#96]
➜  dynamo git:(master) mix deps.clean
- Cleaning ranch (0.8.2) [git: "git://github.com/extend/ranch.git"]
- Cleaning mimetypes (e9dfab5) [git: "git://github.com/spawngrid/mimetypes.git"]
- Cleaning hackney (0.4.0) [git: "git://github.com/benoitc/hackney.git"]
- Cleaning cowboy (0.8.4) [git: "git://github.com/extend/cowboy.git"]
  ➜  dynamo git:(master) MIX_ENV=test mix do deps.get, test
- Getting cowboy [git: "git://github.com/extend/cowboy.git"]
  Cloning into 'deps/cowboy'...
  remote: Counting objects: 4951, done.
  remote: Compressing objects: 100% (2517/2517), done.
  remote: Total 4951 (delta 3111), reused 4153 (delta 2380)
  Receiving objects: 100% (4951/4951), 3.06 MiB | 1.38 MiB/s, done.
  Resolving deltas: 100% (3111/3111), done.
  Checking connectivity... done
- Getting hackney [git: "git://github.com/benoitc/hackney.git"]
  Cloning into 'deps/hackney'...
  remote: Counting objects: 715, done.
  remote: Compressing objects: 100% (256/256), done.
  remote: Total 715 (delta 476), reused 682 (delta 445)
  Receiving objects: 100% (715/715), 328.91 KiB | 0 bytes/s, done.
  Resolving deltas: 100% (476/476), done.
  Checking connectivity... done
- Getting mimetypes [git: "git://github.com/spawngrid/mimetypes.git"]
  Cloning into 'deps/mimetypes'...
  remote: Counting objects: 189, done.
  remote: Compressing objects: 100% (94/94), done.
  remote: Total 189 (delta 101), reused 171 (delta 85)
  Receiving objects: 100% (189/189), 148.92 KiB | 0 bytes/s, done.
  Resolving deltas: 100% (101/101), done.
  Checking connectivity... done
- Getting ranch [git: "git://github.com/extend/ranch.git"]
  Cloning into '/Users/wchrisjohnson/code/dynamo/deps/ranch'...
  remote: Counting objects: 544, done.
  remote: Compressing objects: 100% (323/323), done.
  remote: Total 544 (delta 344), reused 384 (delta 215)
  Receiving objects: 100% (544/544), 153.96 KiB | 0 bytes/s, done.
  Resolving deltas: 100% (344/344), done.
  Checking connectivity... done
  [WARNING] Regex version requirement for dependencies is deprecated, please use Mix.Version instead
- Compiling ranch
  ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_listener_sup.erl ranch_protocol.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
  APP    ranch.app.src
- Compiling mimetypes
  ==> mimetypes (compile)
  Compiled src/mimetypes_scan.xrl
  Compiled src/mimetypes_parse.yrl
  Compiled src/mimetypes_app.erl
  Compiled src/mimetypes_loader.erl
  Compiled src/mimetypes.erl
  Compiled src/mimetypes_sup.erl
  Compiled src/mimetypes_parse.erl
  Compiled src/mimetypes_scan.erl

=INFO REPORT==== 8-Jul-2013::15:10:29 ===
    application: mimetypes
    exited: stopped
    type: temporary
- Compiling hackney
  ==> Entering directory `/Users/wchrisjohnson/code/dynamo/deps/mimetypes'
  ==> Leaving directory`/Users/wchrisjohnson/code/dynamo/deps/mimetypes'
  ==> hackney (compile)
  Compiled src/hackney_transform.erl
  Compiled src/hackney_app.erl
  Compiled src/hackney_deps.erl
  Compiled src/hackney_form.erl
  Compiled src/hackney_headers.erl
  Compiled src/hackney_multipart.erl
  Compiled src/hackney_pool.erl
  Compiled src/hackney.erl
  Compiled src/hackney_request.erl
  Compiled src/hackney_sup.erl
  Compiled src/hackney_ssl_transport.erl
  Compiled src/hackney_tcp_transport.erl
  Compiled src/hackney_response.erl
  Compiled src/hackney_util.erl
  Compiled src/hackney_url.erl
- Compiling cowboy
  ==> Entering directory `/Users/wchrisjohnson/code/dynamo/deps/ranch'
  ==> Leaving directory`/Users/wchrisjohnson/code/dynamo/deps/ranch'
  ==> cowboy (compile)
  Compiled src/cowboy_http_handler.erl
  Compiled src/cowboy_loop_handler.erl
  Compiled src/cowboy_middleware.erl
  Compiled src/cowboy_sub_protocol.erl
  Compiled src/cowboy_websocket_handler.erl
  Compiled src/cowboy_app.erl
  Compiled src/cowboy.erl
  Compiled src/cowboy_bstr.erl
  Compiled src/cowboy_clock.erl
  Compiled src/cowboy_client.erl
  Compiled src/cowboy_multipart.erl
  Compiled src/cowboy_handler.erl
  Compiled src/cowboy_protocol.erl
  Compiled src/cowboy_http.erl
  Compiled src/cowboy_router.erl
  Compiled src/cowboy_static.erl
  Compiled src/cowboy_sup.erl
  Compiled src/cowboy_req.erl
  Compiled src/cowboy_rest.erl
  Compiled src/cowboy_websocket.erl
- Compiling hackney
  ==> Entering directory `/Users/wchrisjohnson/code/dynamo/deps/mimetypes'
  ==> Leaving directory`/Users/wchrisjohnson/code/dynamo/deps/mimetypes'
  ==> hackney (compile)
- Compiling cowboy
  ==> Entering directory `/Users/wchrisjohnson/code/dynamo/deps/ranch'
  ==> Leaving directory`/Users/wchrisjohnson/code/dynamo/deps/ranch'
  ==> cowboy (compile)
  Compiled lib/dynamo/app.ex
  Compiled lib/dynamo/base.ex
  Compiled lib/dynamo/connection/behaviour.ex
  Compiled lib/dynamo.ex
  Compiled lib/binary/dict.ex
  Compiled lib/dynamo/connection/query_parser.ex
  Compiled lib/dynamo/cowboy.ex
  Compiled lib/dynamo/connection/utils.ex
  Compiled lib/dynamo/cowboy/body_parser.ex
  Compiled lib/dynamo/cowboy/handler.ex
  Compiled lib/dynamo/filters/exceptions/public.ex
  Compiled lib/dynamo/filters/head.ex
  Compiled lib/dynamo/filters/loader.ex
  Compiled lib/dynamo/exceptions.ex
  Compiled lib/dynamo/filters/exceptions.ex
  Compiled lib/dynamo/connection.ex
  Compiled lib/dynamo/filters/static.ex
  Compiled lib/dynamo/filters/session.ex
  Compiled lib/dynamo/filters/session/stores.ex
  Compiled lib/dynamo/helpers.ex
  Compiled lib/dynamo/helpers/escaping.ex
  Compiled lib/dynamo/helpers/content_for.ex
  Compiled lib/dynamo/helpers/render.ex
  Compiled lib/dynamo/cowboy/connection.ex
  Compiled lib/dynamo/http.ex
  Compiled lib/dynamo/connection/test.ex
  Compiled lib/dynamo/http/cookies.ex
  Compiled lib/dynamo/http/halt.ex
  Compiled lib/dynamo/http/case.ex
  Compiled lib/dynamo/http/redirect.ex
  Compiled lib/dynamo/http/hibernate.ex
  Compiled lib/dynamo/http/render.ex
  Compiled lib/dynamo/http/session.ex
  Compiled lib/dynamo/loader/error_handler.ex
  Compiled lib/dynamo/router.ex
  Compiled lib/dynamo/router/filters.ex
  Compiled lib/dynamo/filters/exceptions/debug.ex
  Compiled lib/dynamo/loader.ex
  Compiled lib/dynamo/supervisor.ex
  Compiled lib/dynamo/router/utils.ex
  Compiled lib/dynamo/static.ex
  Compiled lib/dynamo/router/base.ex
  Compiled lib/dynamo/templates/handler.ex
  Compiled lib/dynamo/templates/renderer.ex
  Compiled lib/dynamo/templates/finder.ex
  Compiled lib/dynamo/utils/once.ex
  Compiled lib/dynamo/utils/message_verifier.ex
  Compiled lib/mix/tasks/dynamo.filters.ex
  Compiled lib/mix/tasks/compile.dynamo.ex
  Compiled lib/dynamo/templates.ex
  Compiled lib/mix/tasks/server.ex
  Compiled lib/mix/tasks/dynamo.ex
  Generated dynamo.app
  ....................................................................................................................................
  =ERROR REPORT==== 8-Jul-2013::15:10:43 ===
    Conn: GET /other
  Reason: (Dynamo.NotFoundError) no route found
  Stacktrace:
  test/dynamo/cowboy/router_test.exs:6: Dynamo.Cowboy.RouterTest.RouterApp.dispatch/3
  lib/dynamo/filters/exceptions.ex:15: Dynamo.Filters.Exceptions.service/3
  lib/dynamo/cowboy/handler.ex:15: Dynamo.Cowboy.Handler.init/3
  src/cowboy_handler.erl:69: :cowboy_handler.handler_init/4
  src/cowboy_protocol.erl:514: :cowboy_protocol.execute/4
  .......................................................................................................

Finished in 14.5 seconds (3.5s on load, 10.9s on tests)

**Comment by josevalim** [comment]
Oh, that's not an actual error, I will mute it soon, you are "good to go". :)

**Comment by wchrisjohnson** [comment]
Sweet! Thanks ...

**Comment by catsby** [comment]
Can we close this then?

**Comment by wchrisjohnson** [comment]
OK by me.
