### ISSUE TITLE
Deploy crashes on heroku

### ISSUE THREAD

**Issue by cheeyeo** [dynamo/dynamo#99]
Using the latest versions of Elixir and Dynamo and following the deploy to heroku instructions provided, the app crashes with the following error message:

```
'Elixir.RuntimeError','__exception__',
2013-07-19T14:50:42.792444+00:00 app[web.1]:                             
<<"could not find OTP app tasksapp for Tasksapp.Dynamo. This may happen if the directory name is different than the application name."

```

The app is called Tasksapp in this case. It has not been changed in anyway and was created using the mix dynamo command.

nothing else has been added to the app - its a vanilla install

any help appreciated! thanks

**Comment by josevalim** [comment]
It is probably related to the discussion happening here:

https://github.com/elixir-lang/elixir/issues/1046#issuecomment-21233168
